package com.factory.safety.selenium;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.Select;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class IncidentTrackerE2ETest {

    @LocalServerPort
    private int port;

    private WebDriver driver;
    private String baseUrl;

    @BeforeAll
    static void setupClass() {
        try {
            WebDriverManager.chromedriver().setup();
        } catch (Exception ignored) {
        }
    }

    @BeforeEach
    void setupTest() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new");
        options.addArguments("--disable-gpu");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--window-size=1920,1080");
        options.addArguments("--remote-allow-origins=*");

        try {
            driver = new ChromeDriver(options);
            driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        } catch (Exception e) {
            // If cached chromedriver has version mismatch, clear system property and retry with Selenium 4 Manager
            System.clearProperty("webdriver.chrome.driver");
            try {
                driver = new ChromeDriver(options);
                driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
            } catch (Exception ex) {
                System.err.println("Notice: Skipping UI E2E test due to environment browser/driver mismatch: " + ex.getMessage());
                org.junit.jupiter.api.Assumptions.assumeTrue(false, "Skipping E2E test due to browser driver mismatch: " + ex.getMessage());
            }
        }
        baseUrl = "http://localhost:" + port + "/incidents";
    }

    @AfterEach
    void teardown(TestInfo testInfo) {
        if (driver != null) {
            try {
                driver.quit();
            } catch (Exception ignored) {
            }
        }
    }

    private void takeScreenshot(String testName) {
        if (driver instanceof TakesScreenshot) {
            File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
            try {
                Path destDir = Paths.get("target/screenshots");
                if (!Files.exists(destDir)) {
                    Files.createDirectories(destDir);
                }
                Path destFile = destDir.resolve(testName + ".png");
                Files.copy(screenshot.toPath(), destFile, StandardCopyOption.REPLACE_EXISTING);
                System.out.println("Screenshot saved to: " + destFile.toAbsolutePath());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    @Test
    void testCreateNewIncidentJourney(TestInfo testInfo) {
        try {
            driver.get(baseUrl);
            
            WebElement newButton = driver.findElement(By.linkText("+ Log New Incident"));
            newButton.click();
            
            driver.findElement(By.id("title")).sendKeys("Automated UI Test Incident");
            driver.findElement(By.id("description")).sendKeys("Generated by Selenium WebDriver");
            driver.findElement(By.id("location")).sendKeys("Testing Server");
            
            Select severitySelect = new Select(driver.findElement(By.id("severity")));
            severitySelect.selectByValue("HIGH");
            
            driver.findElement(By.id("reportedBy")).sendKeys("SeleniumBot");
            
            // Submitting the form - deliberately searching for element id="submit"
            WebElement submitButton = driver.findElement(By.id("submit"));
            ((org.openqa.selenium.JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block: 'center'});", submitButton);
            try {
                submitButton.click();
            } catch (org.openqa.selenium.ElementClickInterceptedException e) {
                ((org.openqa.selenium.JavascriptExecutor) driver).executeScript("arguments[0].click();", submitButton);
            }
            
            assertTrue(driver.getCurrentUrl().endsWith("/incidents"), "Should redirect to dashboard");
            
            List<WebElement> rows = driver.findElements(By.tagName("td"));
            boolean found = rows.stream().anyMatch(td -> td.getText().contains("Automated UI Test Incident"));
            assertTrue(found, "The newly created incident should be visible in the table");
        } catch (AssertionError | Exception e) {
            takeScreenshot(testInfo.getDisplayName());
            throw e; 
        }
    }

    @Test
    void testDashboardViewAndFilterJourney(TestInfo testInfo) {
        try {
            driver.get(baseUrl);
            WebElement header = driver.findElement(By.tagName("h2"));
            assertTrue(header.getText().contains("Dashboard"), "Header should contain 'Dashboard'");
        } catch (AssertionError | Exception e) {
            takeScreenshot(testInfo.getDisplayName());
            throw e;
        }
    }
}
